ALTER TABLE households ADD COLUMN snacks INTEGER NOT NULL DEFAULT 0;
ALTER TABLE plan_entries ADD COLUMN scale REAL NOT NULL DEFAULT 1;
ALTER TABLE menu_entries ADD COLUMN scale REAL NOT NULL DEFAULT 1;
