import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';

const hash = createHash('sha256');
for (const f of ['public/styles.css', 'public/app.js']) hash.update(readFileSync(f));
const v = hash.digest('hex').slice(0, 10);
writeFileSync('src/assetv.js', `// Generated by scripts/asset-version.mjs — do not edit.\nexport const ASSET_V = '${v}';\n`);
console.log(`ASSET_V=${v}`);
